### ISSUE TITLE
Urlscan breaks parent process (alot) when using clipboard.

### ISSUE THREAD

**Issue by mmartin** [firecat53/urlscan#106]
After launching urlscan from [alot](https://github.com/pazz/alot/) (also an urwid application) and using clipboard functionality (xclip), when I quit urlscan and return to alot it is left in a broken state:
* keybindings no longer work;
* every keypress is printed out on the screen;
* the only way out is Ctrl-C.

Opening URLs (xdg-open) works just fine.

I have a fix in my repo (https://github.com/mmartin/urlscan/commit/68f77d894a9480c8a37090f2f518672be732fcb1), but I'm not quite sure why it works, though.

Maybe You have an idea what is happening and/or are willing to merge my fix?

**Comment by firecat53** [comment]
To be honest, I'm not sure why that fix works either! But, it didn't break
anything that I can see. How did you figure it out?

**Comment by mmartin** [comment]
Trial and error, unfortunately.
