### ISSUE TITLE
urlscan opens links in Firefox even though $BROWSER is set to qutebrowser

### ISSUE THREAD

**Issue by Hund** [firecat53/urlscan#113]
I'm not sure if I'm doing something wrong here or what, but urlscan opens my links in Firefox even thought I have the variable `$BROWSER` set to `qutebrowser --target private-window`:

```
$ echo $BROWSER
qutebrowser --target private-window
```

I'm running version 0.9.6 on Gentoo.

**Comment by wbob** [comment]
I had `xdg-settings get default-web-browser` accidentally set to something different, maybe check this too?

**Comment by Hund** [comment]
> It looks like the python browser module doesn't handle the extra arguments.
> Perhaps try some different quoting schemes or put the whole thing into a small
> shell script and set BROWSER to the shell script name. I know that works because
> that's what I've always done :)

I created the file `browser.sh`with the content:

```bash
#!/bin/bash
qutebrowser --target private-window
```

And then changed the variable to `export BROWSER="browser.sh"`. This did not work, it still opens the links in the wrong web browser.

**Comment by firecat53** [comment]
Does that mean it's working properly now with the small script? That's what I've done for years.

**Comment by Hund** [comment]
> Does that mean it's working properly now with the small script? That's what I've done for years.

Yes, it does. It seems like I was in a hurry, I didn't even said thanks.

Thank you!

**Comment by Hund** [comment]
This (the workaround with the script) doesn't work for me with Debian. I can't make it not open links in Firefox. :(
