### ISSUE TITLE
Clipboard clears after exit

### ISSUE THREAD

**Issue by Farzat07** [firecat53/urlscan#119]
This seems to be a problem with the way X handles the clipboard in general, as explained in [this page](https://wiki.ubuntu.com/ClipboardPersistence), and [this issue on stackoverflow](https://stackoverflow.com/questions/6453595/prevent-vim-from-clearing-the-clipboard-on-exit).

The recommended workaround seems to be using a clipboard manager, so I'll probably do that. I'm mainly opening this for people's reference. Also there seems to be workarounds to fix this from the program level as well, but not sure if they should be implemented.

**Comment by firecat53** [comment]
I'm not seeing this problem at all running i3. I can open mutt, copy a link to
the clipboard with urlscan, close urlscan, close mutt and still paste the
results multiple times.

Not sure exactly what issue you are seeing?

**Comment by Farzat07** [comment]
It is not like the problem always happens - but it used to happen more often than not in my case.

Now that I'm using [clipmenu](https://github.com/cdown/clipmenu) though it stopped happening.

Seems that the problem doesn't happen to many people though, given that I am the first one opening this here. That's why I opened this: to let other people know that the problem is with X and that they should probably get a clipboard manager, as I was myself confused when it happened to me and there was no related issue in the tracker to help me figure it out.
