### ISSUE TITLE
commit 91c99a4 is not part of 0.9.8 release files.

### ISSUE THREAD

**Issue by Avinesh** [firecat53/urlscan#121]
https://github.com/firecat53/urlscan/commit/91c99a4ef90b278956387efb0a6380a8db3394eb
I think this commit changes should be part of the tar files of 0.9.8 release.

**Comment by firecat53** [comment]
Oops, good catch, thanks! I messed up the release process because I haven't
automated it yet!!

**Comment by Avinesh** [comment]
Happy to help!
