### ISSUE TITLE
strip whitespaces

### ISSUE THREAD

**Issue by balejk** [firecat53/urlscan#124]
I am using `urlscan` with `neomutt` and I received a HTML email, where the `href` attribute of the `a` HTML tag contains trailing and leading spaces. `urlscan` extracts the link along with the spaces, which causes `xdg-open` to consider it a filename rather than URL (specifically, the leading spaces cause the problem) and fail with `file '...' does not exist`.

Arguably, `urlscan` should always strip additional whitespaces from links as they are mostly not of interest (although apparently they are allowed in`href`s and can be taken advantage of for example for styling, see [here](https://www.impressivewebs.com/leading-trailing-spaces-html-attribute-values/)) or at least offer a command line option to enable this behaviour.

**Comment by firecat53** [comment]
Stripping spaces sounds reasonable. Do you have a real example URL that I can
use to test with?

**Comment by balejk** [comment]
This is the most stripped down email message where it occurs:
```email
Date: Mon, 1 Jan 1970 00:00:00 +0000 (UTC)
Content-Type: text/html; charset=UTF-8

<a href="                          http://example.net/                        ">example</a>
```

**Comment by firecat53** [comment]
Interestingly, urlscan and xdg-open seem to handle that case just fine on my machine (Sway/Alacritty/Qutebrowser). This is what it looks like (you can see just one space before the URL)(I substituted google.com for the URL to have something to open):

![image](https://user-images.githubusercontent.com/568113/162628146-0c2dc1b7-1b43-47b0-9201-cc6656e5971f.png)

However, both xdg-open and the python built in link opener handle it correctly.

**Comment by balejk** [comment]
What does your input look like in full? Based on the context shown I believe it only contains the `a` HTML tag - please note that `urlscan` does not recognize that as HTML but simply as plain text and extracts the URL without parsing it as HTML (supposedly using some URL regular expression) which leads to spaces not being included.

This is why the `Content-Type` header in my example above is important (and the `Date` header is important as well - without it, `urlscan` does not seem to recognize that the input is in a header-content format and hence does not parse the `Content-Type` header and does not treat the content as HTML - specifying the `From` header instead seems to work as well so supposedly there just needs to be some other (arbitrary) header besides `Content-Type`).

**Comment by firecat53** [comment]
Ah, shoot. I had a leading space in front of the Content-Type header so it didn't get recognized. I see what you're seeing now!

**Comment by firecat53** [comment]
I pushed a fix to the develop branch. See if that works for you.

**Comment by balejk** [comment]
Yes, this seems to work, thank you!
