### ISSUE TITLE
URLs with * are not parsed correctly

### ISSUE THREAD

**Issue by fcladera** [firecat53/urlscan#125]
First of all, thanks for this amazing piece of software. I am facing an issue with the current version of `urlscan`. Some corp emails use services to rewrite URLs, such as [urldefense.com](urldefense.com). `urlscan` is having trouble when there is a * in the url.

Example
```
http://url_safe.com/__http://myurl.com/test&opt=AB*C
```
urlscan parses:
```
http://url_safe.com/__http://myurl.com/test&opt=AB
```
Thanks!

**Comment by firecat53** [comment]
I pushed a commit to develop that should allow the '*'. Let me know that it works for you.

**Comment by fcladera** [comment]
It seems to be working fine. Thanks!!
