### ISSUE TITLE
Add support for IPv6 URLs

### ISSUE THREAD

**Issue by wvdongen** [firecat53/urlscan#127]
Although perhaps rarely used, I think it would also be nice to also support IPv6 URLs:

```sh
echo "http://[2a07:3500:11a0:320::22]:8080 and http://10.0.0.1:8080" | urlscan -n
````
Currently only detects `http://10.0.0.1:8080`. 

Just some background info on IPv6 in URLs: <https://datatracker.ietf.org/doc/html/rfc2732>

After a quick Google search, this appears to be a regex compliant to find IPv6 addresses. By modifying the regex to include the obviously the schema and the required `[`, `]` chars (see the RFC) this could perhaps be easily added. Please note, that I haven't tested this at all, there might be far better regexes available and obviously, I don't know what the impact is on the rest of the functionality of urlscan.

**Comment by firecat53** [comment]
I pushed a commit that hopefully will work for IPv6 URLs and not break anything else! Give it a try (develop branch) if you can and let me know. Sorry it took so long!

**Comment by wvdongen** [comment]
@firecat53 many thanks for the feature! Could you push a new version to https://pypi.org/?

**Comment by firecat53** [comment]
Done. 1.0.0 released on pypi.
