### ISSUE TITLE
Search does not work with `-c` flag

### ISSUE THREAD

**Issue by sanjayankur31** [firecat53/urlscan#131]
When using the `-c` flag, using `/` to search does not work. A new line (footer) with "Search:" does start, but on typing, no letters are reflected there and no search occurs. Removing the `-c` flag from the command invocation makes search work again.

```
$ rpm -q urlscan
urlscan-0.9.10-2.fc38.noarch

$ python --version
Python 3.11.3

```

To reproduce:

- cat <any file with urls> | urlscan -d -c
- try to search

**Comment by firecat53** [comment]
I can reproduce this, thanks! I haven't found the problem yet, though.

**Comment by firecat53** [comment]
Pushed a fix to the develop branch. Let me know if that works for you.

Good find! That was a challenge to track down.

**Comment by sanjayankur31** [comment]
Yes, that fixes it.  Thanks very much for the quick response :rocket:
