### ISSUE TITLE
neomutt curses term database not found error - fix

### ISSUE THREAD

**Issue by tjex** [firecat53/urlscan#135]
Just wanted to quickly bring to attention a fix to an issue I've just encountered. I'm on a mac, but still generally applicable as it has to do with xterm definitions / profiles. 

Truecolor (256 colors) became supported as of the latest neomutt release. However to enable this, we currently need to execute `TERM=xterm-direct neomutt` to use the colors properly. [see here](https://github.com/neomutt/neomutt/releases/tag/20230517).

I found that when running `urlscan`, I was getting an error `setupterm: could not find terminfo database`. And this was because there is no term definition for xterm-direct. I'm not actually sure how the xterm-direct even works with loading 256 colors... With `TERM=xterm-256color`, neomutt does not load the colors properly. Very confusing, and there are not other suggestions from the devs as to other ways to execute / run colors properly - hence the following fix.

I couldn't find a definition for xterm-direct to download (?), so I did a quick and dirty addition to the suggested macro command from the wiki:

`macro index,pager \cb "<pipe-message>  urlscan<Enter>" "call urlscan to extract URLs out of a message"` 

becomes

`macro index,pager  \cb "<pipe-message>  TERM=xterm-256color urlscan<Enter>" "call urlscan to extract URLs out of a message"`

`urlscan` runs then as expected

if it's worth it, I can make a pr and add this to the readme.

**Comment by firecat53** [comment]
The issue appears to be that the regex is only applied to the plain text part of the message, not the HTML part. This will take some digging to solve...

**Comment by firecat53** [comment]
Sure, sounds like a reasonable documentation update. Thanks! And sorry for the _very_ slow response...

**Comment by firecat53** [comment]
Are you still planning on submitting a documentation update or is this no longer an issue? Thanks!

**Comment by tjex** [comment]
Hey, sorry my mistake for not linking the issue in the pr, but it's already done :) - pr #136
