### ISSUE TITLE
Forwarded: Monochrome version with arrow to visualize the selected entry.

### ISSUE THREAD

**Issue by xakz** [firecat53/urlscan#17]
Forwarded from: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=406013

---

I just figured out that the arrow keys change between the different
URLs before <enter> opens it. However, the default colours make it
impossible to determine which URL is currently selected. Would it be
possible to adjust the colours? Why not make it less colourful and
add more contrast?

---

The bug report was not obvious to understand for me. In fact, the submitter wants a monochrome version, with, if possible, an arrow or any other character on the screen to visualize which line is selected. So tag it as feature request please.

I done some search about urwid, it appears hard to me to implement that without any modification inside urwid. So, this feature is probably not for tomorrow.

**Comment by firecat53** [comment]
Better late than never :smile: Do you think this commit addresses the bug report adequately?

Thanks!
