### ISSUE TITLE
Firefox stopped opening URLs properly

### ISSUE THREAD

**Issue by robertsawko** [firecat53/urlscan#22]
Hello,

I used urlscan for sometime now (thanks!) and it still works okay on my laptop but after installing the latest version from AUR it stopped working properly with firefox. When I run urlscan on this example

```
This is a link
https://www.google.com
```
and select the link I get "Problem loading page: File not found". Looking at the location bar reveals that firefox tried top open `file:///home/c111269/openURL(https://www.google.com)`. Removing the unnecessary symbols helps of course, but it defeats the purpose slighlty. Can you let me know if you're aware what may have gone wrong?

**Comment by firecat53** [comment]
1. What version of python and urwid are you using?

2. Are there any old urlscan libraries in /usr/lib/python3.4/site-packages (or python2.x/3.x), or in $HOME/.local/lib/python3.4/site-packages?

3. Are you using any kind of wrapper script to launch your web browser?

4. Create a file 'test' with the contents you tested with above and run urlscan with the -n flag. Does it output https://www.google.com ?

FWIW, I'm running urlscan-git from the AUR right now with zero problems.

Scott

**Comment by robertsawko** [comment]
Hello Scott,

sorry for the late response. I am running the same urlscan-git on my desktop and laptop. On laptop it works without any problems. I am trying to find what's the difference.

Re your questions

1. It's python 3.4, I just reinstalled urlscan and urwid so I have
   `Packages (2) python-urwid-1.3.0-1  urlscan-git-r49.f0ae093-1`
1. No as far as I can see.
1. I don't think so.
1. Yes it outputs https://www.google.com

I also get correct behaviour on chromium when I change the `BROWSER` variable, so it's just firefox. The only awkward plugin I am using is vimperator but I switched that off and the behaviour was the same.

**Comment by firecat53** [comment]
I'm not quite sure how to help. Sounds to me like more a Firefox problem than a urlscan problem since it works correctly from the command line and from Chromium. Sorry I can't be more help!

**Comment by robertsawko** [comment]
Thanks, yes it seems my personal settings on the machines are causing this. Can I ask you to look at this [one](https://bbs.archlinux.org/viewtopic.php?id=195810)? I think I managed to narrow down the problem to my python settings or installation.

In addition when I type `firefox [url]` from the command line it correctly opens the url. It is only when I do it from the webbrowser module that this strange `openURL` prefix breaks in.

**Comment by firecat53** [comment]
Closing this issue...not a urlscan problem. Troubleshooting in the forum thread linked in the previous post.
