### ISSUE TITLE
Installation problem on Ubuntu

### ISSUE THREAD

**Issue by nlw0** [firecat53/urlscan#23]
Hi, I'm trying to install urlscan using "sudo pip install". It all seems to work well, but then I get 

        error: can't copy 'COPYING': doesn't exist or not a regular file

Any ideas?

**Comment by firecat53** [comment]
I just tried this on my Ubuntu 14.04 server and it worked fine...no errors. Perhaps make sure you're not using a cached copy of the installation .whl or .egg from somewhere in your filesystem. Maybe try downloading the .whl file directly from pypi and installing it. I can't think of any other reasons it would fail!

Scott

**Comment by firecat53** [comment]
Closing. You can reopen if you are still having issues.

Thanks,
Scott
