### ISSUE TITLE
locale.setlocale(locale.LC_ALL, '') does not work in Mac OS

### ISSUE THREAD

**Issue by khapota** [firecat53/urlscan#25]
locale.Error: unsupported locale setting

**Comment by firecat53** [comment]
Does anything [here](http://stackoverflow.com/questions/1629699/locale-getlocale-problems-on-osx) help at all? Sorry, but I have no Macs for testing on or any experience with Macs.

**Comment by khapota** [comment]
Thanks. I added:
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```
to my bashrc and it works.

**Comment by khapota** [comment]
Hi, it will work for MacOs with this code:
```
locale.setlocale(locale.LC_ALL)
```
omit [locale] follow this document:
https://docs.python.org/2/library/locale.html#locale.setlocale

Please check with other OS. Thanks.

**Comment by firecat53** [comment]
I think that this is just a matter of making sure your environment is setup correctly. `setlocale(locale.LC_ALL, '')` per the docs you linked sets the locale "for all categories to the user's default settings". Given that, I'm going to close this issue, as it seems more an environment issue than a code issue. If you have a different take, feel free to reopen with more information.

Thanks!
Scott
