### ISSUE TITLE
URL in markdown-formated emails are not extracted correctly

### ISSUE THREAD

**Issue by gwarf** [firecat53/urlscan#27]
Hi,
Probably related to #12 the URLs contained in markdown-formated emails are not extracted correctly.
Markdown URLs are enclosed into round brackets so the URL is extracted with the final round bracket due too
https://github.com/firecat53/urlscan/blob/0.8.1/urlscan/urlscan.py#L248
Markdown URL `[urlscan](https://github.com/firecat53/urlscan/)` is extracted by urlscan as `https://github.com/firecat53/urlscan/)` and the closing parenthesis breaks the URL.
Thanks,
Baptiste

**Comment by firecat53** [comment]
Does a markdown formatted email get sent as text/plain or text/html? Do you have an example you can send (either forward it to me, or put the original in a tar archive to preserve encoding and formatting)?

Do you or @xakz have any thoughts about how to implement this without breaking the changes in b8e3b5f9? Currently both text/html and text/plain messages use the same regex for url detection.

Thanks,
Scott

**Comment by xakz** [comment]
I think the matching algorithm should be modified to become recursive to eliminate enclosing character pair ( [], {}, (), "", '', ``, `', <> ) first, and then seek for url regexp in the resulting output.

I'm far from urlscan actually, but later, I will look about that (if not already fixed).

**Comment by tobanw** [comment]
I'm running into the same trailing `)` problem with markdown links when using [Reddit Terminal Viewer](https://github.com/michael-lazar/rtv/) with urlscan. As @xakz mentioned, it needs to strip off enclosing delimiters first.

**Comment by firecat53** [comment]
Yes it does...easier said than done :smile: I'll have another go at it when I get a chance (unless someone beats me to it).

**Comment by firecat53** [comment]
Well, as a fix for _most_ markdown links, just removing the close parentheses from the urltrailingpattern variable seems to work (see commit 2d54124a7). I'm inclined to push this as a fix because trying to completely overhaul the matching algorithm is very hard. 

The only URLs it won't correctly parse are ones with a close parentheses at the end of link like:

    [My Link](<http://example.com/test(1)>)
    with [parens at end](http://example.com/test(1))
    http://example.com/test_(test)

It will still correctly parse Markdown URLs and URLs with a close parentheses in the middle of the URL:

    [Watson](http://tailordev.github.io/Watson/)
    with [parens](http://example.com/test(1).html)
    http://example.com/test(1).html
    http://msdn.microsoft.com/en-us/library/aa752574(VS.85).aspx

I think I'm willing to accept the very few URLs that won't get correctly parsed to avoid a rewrite!

Thoughts?

**Comment by firecat53** [comment]
I'm going to go ahead and merge this. It at least fixes the issue of parsing most Markdown URLs correctly near as I can tell. Let me know if anyone has a better way!

**Comment by anhtuann** [comment]
In your example, @firecat53 , the first markdown link isn't parsed by urlscan 0.8.6
`[Watson](http://tailordev.github.io/Watson/)`
`with [parens](http://example.com/test(1).html)`
`http://example.com/test(1).html`
`http://msdn.microsoft.com/en-us/library/aa752574(VS.85).aspx`

**Comment by firecat53** [comment]
@anhtuann sure it is...there just happens to be a little bug sometimes where if you don't put a blank line at the top of the file, it'll ignore a link on the first line :smile:

**Comment by anhtuann** [comment]
Oh ok, I see ahahah. Problem is, your urlscan is used in another context to extract urls in [reddit terminal viewer](https://github.com/michael-lazar/rtv) and urls in first line of reddit comments appear all the time :)

**Comment by firecat53** [comment]
Oh, cool! I didn't know that! I'll open a  separate issue and get that fixed, then.

**Comment by firecat53** [comment]
@anhtuann can you please send me an example of a reddit page/post where this happens if you can. I just want to make sure it works with a real world example as well as the toy example above. Thanks!

**Comment by anhtuann** [comment]
Hum it's hard to send you that. The reddit webserver renders markdown in html so if I send you a link, you wouldn't get the markdown. The only way would be for you to install reddit terminal viewer and try on a link I send you. Anyway, here is the snippet that made me notice urlscan wouldn't work.
```
Wallpaper: [here](http://www.qygjxz.com/typography-wallpaper/5274557.html)
DE: GNOME
GTK: Arc-Dark
Icons: Papirus-Dark
Terminal: Termite
and obligatory neofetch
```

The [permalink is here](https://www.reddit.com/r/unixporn/comments/77r1sj/a_step_away_from_windows_gnome/doo1kek/)

**Comment by firecat53** [comment]
Ah, I see...thanks!
