### ISSUE TITLE
Readme Hides '\' in Render

### ISSUE THREAD

**Issue by psycotica0** [firecat53/urlscan#29]
Hey guys.
In your README file you have the configuration example of:

    bind \cb STUFF

But when github renders it to show casual seekers such as myself, the backslash is omitted, so it looks like:

    bind cb STUFF

This didn't work for me and I didn't know why.
I had to read the mutt documentation to figure out what it should look like, then once I knew I thought "Oh, it's backslash, I bet that's just getting removed", which it was.

**Comment by firecat53** [comment]
Thanks!
