### ISSUE TITLE
rpmlint: incorrect-fsf-address error

### ISSUE THREAD

**Issue by fszymanski** [firecat53/urlscan#31]
Hi,
I created today an RPM package for Fedora, but after running [rpmlint](https://github.com/rpm-software-management/rpmlint) I'm getting three errors:
```
urlscan.noarch: E: incorrect-fsf-address /usr/bin/urlscan
urlscan.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/urlscan/urlscan.py
urlscan.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/urlscan/urlchoose.py
```
This is not a [blocker](http://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address) (bug) but I have to inform the upstream. Can you update the FSF address in these files?

P.S.
My Fedora Copr [repo](https://copr.fedorainfracloud.org/coprs/fszymanski/urlscan/).

Thanks,
Filip

**Comment by firecat53** [comment]
On Sun, Apr 03, 2016 at 02:56:25PM -0700, Filip Szymański wrote:
>    HI,
>    I created today an RPM package for Fedora, but after running [1]rpmlint
>    I'm getting three errors:
> 
>  urlscan.noarch: E: incorrect-fsf-address /usr/bin/urlscan
>  urlscan.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/urlscan/urlscan.py
>  urlscan.noarch: E: incorrect-fsf-address /usr/lib/python3.5/site-packages/urlscan/urlchoose.py
> 
>    This is not a [2]blocker (bug) but I have to inform the upstream. Can you
>    update the FSF address in these files?

Fixed on the master branch. Thanks!

Scott
