### ISSUE TITLE
Input that begins with valid URL starting with http:// are not correctly parsed

### ISSUE THREAD

**Issue by msmith491** [firecat53/urlscan#36]
Originally found in this thread: https://github.com/firecat53/urlscan/pull/34

Test cases:

Working
`$ echo -e "\nhttp://www.google.com\nhttp://www.reddit.com" | ./bin/urlscan --no-browser`

`$ echo -e "tester\nhttp://www.google.com\nhttp://www.reddit.com" | ./bin/urlscan --no-browser`

`$ echo -e "tester http://www.google.com\nhttp://www.reddit.com" | ./bin/urlscan --no-browser`

`$ echo -e "www.google.com\nhttp://www.reddit.com" | ./bin/urlscan --no-browser`

Not working:
`$ echo -e "http://www.google.com\nhttp://www.reddit.com" | ./bin/urlscan --no-browser`

`$ echo -e "https://www.google.com\nhttp://www.reddit.com" | ./bin/urlscan --no-browser`

**Comment by firecat53** [comment]
Hrm, looks like an artifact of email.Parser. Have to prepend a blank line or word if that first line starts with http*

**Comment by firecat53** [comment]
Give the develop branch a try and see if that fixes it for you.

**Comment by msmith491** [comment]
That changes fixes the issue for me.  Thanks!
