### ISSUE TITLE
Bump to version 0.8.5 in setup.py

### ISSUE THREAD

**Issue by jfrankenau** [firecat53/urlscan#40]
Hello Scott,

I've noticed that you tagged a new version 0.8.5 without updating the `setup.py`. Would be great if you could amend that as I'd like to push the new version for NixOS.

Thank you for urlscan.

**Comment by firecat53** [comment]
Oops. It actually was updated and released, but I forgot to push master to Github! Done.

**Comment by jfrankenau** [comment]
Thank you, that was quick. Is it possible to move the tag to the new commit as well?

**Comment by firecat53** [comment]
0.8.5 is already at the most recent commit on master:

    urlscan $ git rev-list -n 1 0.8.5 
      1c49b08135e2961f25ec27dc69aea19cac1f92d4
    urlscan $ git rev-parse HEAD                                                                                                           
      1c49b08135e2961f25ec27dc69aea19cac1f92d4

**Comment by jfrankenau** [comment]
Not on my end with a fresh clone:

    ~/code/urlscan $ git rev-list -n 1 0.8.5
    263787ec4c599120d9595c8fdd508d7da78df7b4
    ~/code/urlscan $ git rev-parse HEAD
    1c49b08135e2961f25ec27dc69aea19cac1f92d4

See here as well: https://github.com/firecat53/urlscan/releases/tag/0.8.5

**Comment by firecat53** [comment]
Ok, that got mismatched by accident. I just made a new tag and set a new release. I just have to upload the release to pypi, which won't happen for a few hours cause we're just heading out the door. Thanks for noticing!

**Comment by jfrankenau** [comment]
No, problem. Thank you for the new clean release.

**Comment by firecat53** [comment]
Uploaded to pypi.
