### ISSUE TITLE
First URL is sometimes dropped

### ISSUE THREAD

**Issue by firecat53** [firecat53/urlscan#41]
If a URL is the first line in a file it will sometimes not get parsed at all.

**Comment by firecat53** [comment]
@anhtuann can you please test the develop branch? I put a fix in. It has the additional effect of including a mailto link to all the recipients and sender of emails. I'm not sure if that's helpful or not, but make sure to test it on email as well as rtv!  Thanks!

**Comment by anhtuann** [comment]
I tested it in rtv and it seems to work like a charm ! I don't use mutt yet so can't vouch for the email part. Thanks !

**Comment by firecat53** [comment]
Fixed by 3922bde. Behavior for emails should stay the same now (i.e. no mailto: links will be printed for the From and To fields).
