### ISSUE TITLE
Add numeric pad support

### ISSUE THREAD

**Issue by pprw** [firecat53/urlscan#42]
It seems to me that urlscan should allow to select urls with the numbers intergrated to the keyboard. That is to say: when press 5, urlscan open in browser url 5. Now I have to use the arrow keys which is less effective.

**Comment by firecat53** [comment]
Good idea!

**Comment by firecat53** [comment]
Try out the develop branch and see if that works for you.

**Comment by pprw** [comment]
Thanks, I will test it.

I installed by mistake the master branch, I install just after the develop branch but I think it didn't erase the master branch. 

What is the proper way to remove urlscan? I installed the master branch with  ./setup build and ./setup install.

**Comment by firecat53** [comment]
If you installed it locally (as your user, not root), then you have to remove
the urlscan files in ~/.local/bin and ~/.local/lib/pythonx.x/site-packages.

If you experiment much with installing python applications, definitely learn
how to use virtualenv's. They will keep the applications isolated and easy to
uninstall (just delete the virtualenv).

**Comment by pprw** [comment]
Ok I managed to uninstall and install the develop branch.

It works fine. I propose, for maximum efficiency, to remove the step "press enter". You press 2 and the url 2 is loading.

**Comment by firecat53** [comment]
Two reasons why this won't work:

1. There's no way to discern numbers with more than 1 digit.

2. If you type the wrong number it won't automatically launch the url. Gives you a chance to move to the correct one.

**Comment by pprw** [comment]
Yes it makes sense.

<number>+<ENTER> is already a good amelioration. Thanks !
