### ISSUE TITLE
Unreadable urls

### ISSUE THREAD

**Issue by kflak** [firecat53/urlscan#46]
Hi, 

Thanks for a great tool! However, I have a problem reading the urls that are in focus, both when running a dark and a light gruvbox-inspired theme in xfce4-terminal. 
The problem is that the selected links are dark grey on a darkish-blue background, which is obviously a bit hard to make out. I tried this with the default mutt color-scheme, as well as a light and a dark gruvbox-theme. Any solutions much appreciated!
I am on Arch Linux/i3wm

**Comment by firecat53** [comment]
This might take awhile to fix. I have to figure out whether to use command-line switches, a config file, or some way to cycle through colors on the fly. Right now, the palette is hard coded into urlchoose.py (line 155 self.palette). If you can't find a terminal theme that works for you, you could install urlscan from git and play with the colors in self.palette until I can make it configurable.

**Comment by kflak** [comment]
Thanks for the response! Will take a look at the git version when I have 
a bit more time on my hands.

**Comment by firecat53** [comment]
Hey, give the develop branch a try and see what you think. Added a black & white palette and a config file can be generated for editing/adding palettes.

**Comment by kflak** [comment]
Oh sweet! The black and white theme works miracles for visibility. Thanks a lot for this :-)
