### ISSUE TITLE
Add shortcut to scroll to the end and top of the document

### ISSUE THREAD

**Issue by ElDeveloper** [firecat53/urlscan#47]
When viewing a list of URLs (specially with the context enabled), it would be useful to be able to scroll to the bottom with just one keystroke (maybe `G`).

**Comment by firecat53** [comment]
You can currently use the 'Home' and 'End' buttons on your keyboard, or type the last number in the list to jump there directly. I'll look at adding some more 'vim-like' keyboard shortcuts (besides j-k scrolling which is already in place).

**Comment by ElDeveloper** [comment]
Thanks, this is all very useful information! More vim-like shortcuts would be cool. When I use my laptop (a macbook) I don't have the home and end buttons, however I just installed the latest urlscan and saw the jump to URL shortcut, pretty neat ✨

**Comment by ElDeveloper** [comment]
That's brilliant, thanks for looking into this 👍
