### ISSUE TITLE
urlscan overlays the browser window

### ISSUE THREAD

**Issue by basxto** [firecat53/urlscan#48]
When I use `BROWSER=elinks` or `BROWSER=w3m`, the browser opens, but after some time urlscan's interface will be drawn over the browser.

OS: ArchLinux
Terminal: germinal + tmux
Executed as: `tmux capture-pane -p | urlscan -d`

**Comment by firecat53** [comment]
Pushed a fix to the 'develop' branch. Let me know if that works for you!

**Comment by basxto** [comment]
It does work, but it’s buggy.
When you quit the browser and return to urlscan, urlscan does not redraw.
`man awesome | BROWSER=w3m urlscan -d`

**Comment by firecat53** [comment]
Ok, try the develop branch again.
