### ISSUE TITLE
Executing more complex commands

### ISSUE THREAD

**Issue by basxto** [firecat53/urlscan#51]
I tried to give the URLs to more complex commands, which failed.
```
man awesome | BROWSER="tmux save-buffer " urlscan -d
man awesome | BROWSER="notify-send -u critical " urlscan -d
```
Maybe something like `--command -c` would be better for that.
I think, this would make it neccessary to invoke a shell.
```
man awesome | urlscan -c "tmux save-buffer %s" -d
man awesome | urlscan -c "echo %s | xclip -i -sel clipboard" -d
```

**Comment by firecat53** [comment]
Yeah, I definitely want to keep the BROWSER functionality intact because it's an expected interface. I use the webbrowser module to open URLs, which is why the complex commands fail.

**Comment by firecat53** [comment]
Ok, give that a try. The flag is `-r or --run`, and use `{}` to substitute in the URL value.

**Comment by firecat53** [comment]
Works here, so it's merged. You can reopen if it doesn't work like you expect.
