### ISSUE TITLE
Color scheme makes menu unreadable

### ISSUE THREAD

**Issue by machinedgod** [firecat53/urlscan#61]
Hi there,
the curses interface presented by URL scan makes the top menu really unreadable (desaturated blue with gray text, see screenshot). This is of course due to my xlib color scheme (hybrid-dark), but since it looks good in all other software that uses xlib colors, it'd be really great if we could either set the colors ourselves (through commandline switches) or at least have the option of the b/w mode.

If this is something you'd allow in your codebase, I'd be OK to write code on my own.

![2018-05-18-134208_697x364_scrot](https://user-images.githubusercontent.com/5933618/40249541-d59cd204-5ac2-11e8-9c91-50d60e31dfcd.png)

**Comment by firecat53** [comment]
Yep, this is similar to #46. If you'd like to work on it, I'd be happy to discuss options with you (config file vs command line switches, etc.). It's gonna be awhile before I can work on it in depth. Thanks!

**Comment by machinedgod** [comment]
Hey there, yeah I think I can tackle this :-)
So, what did you have in mind, vis-a-vis options?
I myself always prefer switches rather than config files, reasoning behind it is that switch mechanism is standardized and allows configuration to be changed for each instance of software ran, while config files come in all sorts of different flavors (ini, xml, tables, something wonky like asoundrc or irssi), different system paths, and config is shared across instances. Plus, it somewhat feels intuitive to use switches for programs that have a short life.
This being said, I'm totally OK going either way.

**Comment by machinedgod** [comment]
So after short looking, it looks like `urlchoose.py` contains a class URLChooser, which defines a palette, keyed by first element of the tuple.
This could be a parameter to the class, set up as a default with options provided, to extract the options to the construction place. The options themselves, I have few ideas:
- if we go for a config file, they could translate perfectly into an ini file (with a colorscheme header, so its open for extensions with other options)
- we could add a `--colorscheme=` switch whose value follows certain pattern, for example `<key>:<values>, <key>:<values>...`
- we could add a set of `--colorscheme-<key>=` switches whose values are <values>

**Comment by machinedgod** [comment]
Heya, I went to be proactive and figured third option might actually be the best - ability to switch palettes on the fly.
I've added PR here https://github.com/firecat53/urlscan/pull/62

**Comment by firecat53** [comment]
Hey, give the develop branch a try and see what you think. I built on your PR. Added a json config file for editing/adding palettes and changed keybinding to `p` for cycling through palettes.

**Comment by machinedgod** [comment]
Hey! Sorry that it took me this long to get back to you, I was real busy. I run Arch and I've modified my PKGBUILD to check out `develop` branch, reinstalled everything, and it works awesome! I've only QA-ed default 'P' settings (B/W and standard palette), but I'll try toying with custom colorschemes down the line, try and create one that's a better fit for hybrid and send you another PR.

Cheers, and thanks for taking time to implement this.

**Comment by firecat53** [comment]
FYI, I ended up settling on a config file because the palette configuration is so complex it was the only option that made sense.
