### ISSUE TITLE
Customize hotkeys?

### ISSUE THREAD

**Issue by 097115** [firecat53/urlscan#72]
Would be great to have a chance to customize not only colorschemes but also map your own hotkeys in a config file.

**Comment by firecat53** [comment]
I'll take a look. It'll required reworking the way the keys are handled.

**Comment by rslindee** [comment]
I, too, think this would be an great feature!

Personally, I don't like the idea of a config file being generated from a (potentially accidental) keypress and would like to unmap such a feature.

**Comment by firecat53** [comment]
Pushed some changes to the develop branch that allow editing keybindings in config.json. Give it a try and let me know how it works!

**Comment by rslindee** [comment]
Thank you for pursuing this!

Some feedback:

- I went ahead and remapped config_create from "P" to "x". "x" certainly works to create a config file, but the default "P" still works, where I would expect "P" to now do nothing.
- Removing a key doesn't work and the default map/functionality remains. For example, if I delete the line of '"P": "config_create",' the map still exists and functions (when I would expect it not to)
- The help menu does not reflect my changed hotkey mappings (I do not use this feature, but others certainly may)

Thank you again and I hope you find this feedback useful.

**Comment by firecat53** [comment]
I probably need to make it more obvious in the docs, but you need to unmap a key by setting it to "", then remapping it to something else. This should take care of your first two points, I hope. I'm already working on fixing the last point. Thanks!

**Comment by rslindee** [comment]
Hmmm, I tried unmapping the "config_create" key per your suggestion, but the original mapping persists. For example, if I have the following lines:

        "": "config_create",
        "x": "config_create",

"P" still calls "config_create".

**Comment by firecat53** [comment]
Oh, sorry! You need to set `"P": ""` to unset P. That might help :D I didn't immediately notice you had it backwards!

**Comment by firecat53** [comment]
Pushed another commit to develop with significant modifications in displaying help menu, including dynamic keybindings. Let me know how it works!

**Comment by 097115** [comment]
Looks good, thanks!

The only question I have, would it be very difficult to add another hotkey (in addition to `<Enter>`) for actually opening a link? Here's the workflow I have in mind: let's say, from Mutt, you launch `urlscan` with -- let it be -- `<F2>`, then select a link you want to launch with navigation keys, and then, if you defined this alternative launcher, press the same `<F2>` again to open the selected link -- so that you literally don't have to move your left hand :)

Sure, if it's too much work, then simply don't bother. And thanks again!

**Comment by rslindee** [comment]
No worries, I realize I definitely made some goofy assumptions with the key remapping behavior (busy day yesterday). I just tried your latest changes and it looks great.

Thank you for implementing these suggestions and being so patient!

**Comment by firecat53** [comment]
@097115 I added the ability to assign another key to open URLs. Just so you know, both `space` and `enter` work by default (added to docs). Let me know if that works for you (develop branch).

@rslindee great! Thanks for testing.

**Comment by 097115** [comment]
That's great, thanks! (Have done a bit of testing already, everything seems OK)

You will close the issue after pushing it to master?
