### ISSUE TITLE
urls opens in w3m in tmux

### ISSUE THREAD

**Issue by rlue** [firecat53/urlscan#76]
Noticed this problem this morning. Started with v0.8.2 (via Debian repos) and it was working for months. Don't know what changed that caused it to break. Upgraded to v0.9.0 (via pip3), but that doesn't help.

URLs open in firefox with `xdg-open` and with `urlscan` in the bare terminal; in tmux, they open in w3m. `$BROWSER` is not set. Read through issue #70; confirmed that no older versions of `urwid` are installed.

On Debian buster, with python 3.6.7, urlscan installed via both `sudo apt install urlscan` and `sudo pip3 install urlscan --upgrade`

**Comment by rlue** [comment]
It magically went away. -_-'

**Comment by firecat53** [comment]
Sooo...since you're around here recently, would you be able to install the develop branch and test the search feature I added? I really don't have anyone to test it on and I'd like to make sure it's relatively intuitive to use before releasing it. Just thought I'd check! Thanks!

**Comment by rlue** [comment]
Hey sorry for the delay in getting back to you. Looks like you released already, but FWIW, I think it's plenty intuitive.

One problem I have is that I'm using the B/W palette, and search results aren't highlighted until I switch to the colored palette and back again. Maybe this should go into a new issue, but I'm honestly not really complaining.

It may be worth noting that I am on alacritty + tmux on Linux (Debian).

https://youtu.be/6El0GVBGAL8

**Comment by firecat53** [comment]
Thanks for testing! I think you may be testing a version a couple commits behind. I remember having that issue but fixing it. Tried on my machine (Arch/urxvt/tmux) and it works as it should with the B/W palette saved to config.json. Try wiping and reinstall using `pip install --user urlscan`.

**Comment by firecat53** [comment]
Ach, disregard above...just delete the unwanted or duplicate palettes from config.json! I forgot already that's what caused that issue!
