### ISSUE TITLE
Customize regular expression to match URLs

### ISSUE THREAD

**Issue by alter2000** [firecat53/urlscan#79]
I have a couple of use cases here: one that wants only https?:// URLs, one for everything except mailto: links, and any custom protocol prefix. The easiest way to fit all this in is with a custom regex rather than putting them as options. I haven't looked into the code to see how feasible this is and how it works right now, so it might even be easier to create something else entirely to handle custom regexes.  
Or is it already implemented? I didn't see anything in the issues and google.

Anyway, thanks for the work. It's _really_ nice.

**Comment by firecat53** [comment]
All the regex code is in urlscan/urlscan.py lines 261-286. These are the current horrific regexes:

    URLINTERNALPATTERN = r'[{}()@\w/\\\-%?!&.=:;+,#~]'
    URLTRAILINGPATTERN = r'[{}(@\w/\-%&=+#]'
    HTTPURLPATTERN = (r'(?:(https?|file|ftps?)://' + URLINTERNALPATTERN +
                      r'*' + URLTRAILINGPATTERN + r')')
    # Used to guess that blah.blah.blah.TLD is a URL.
    ....
    TLDS = load_tlds()
    GUESSEDURLPATTERN = (r'(?:[\w\-%]+(?:\.[\w\-%]+)*\.(?:' +
                         '|'.join(TLDS) + ')$)')
    URLRE = re.compile(r'(?:<(?:URL:)?)?(' + HTTPURLPATTERN + '|' +
                       GUESSEDURLPATTERN +
                       r'|(?P<email>(mailto:)?[\w\-.]+@[\w\-.]*[\w\-]))>?',
                       flags=re.U)
    
Haven't touched these in quite awhile :D I've avoided adding the complexity of
a config file up to now but I'm not sure a command line option would be
particularly friendly for a regex. Looking at the regexes above, do you have a
sense of what the regex might be to detect the URLs you would be filtering?

**Comment by alter2000** [comment]
Thanks, will check out tomorrow. I guess only the `HTTPURLPATTERN` and [the compile call](https://github.com/firecat53/urlscan/blob/12e0e7e72871615b02b4c0c4bee8d9d1ad26e92e/urlscan/urlscan.py#L285) will have to be modified in the beginning for some of my use cases, but I can make a PR for XDG-compliant config some time next week.

**Comment by firecat53** [comment]
Oof, well I'm kinda dumb...forgot that I added in a config file for people that use different palettes :roll_eyes:  . I don't use it so it slipped my mind! So you could probably add something in there if that makes sense. It's just a json file.

**Comment by alter2000** [comment]
I've looked at urlchooser.py and as far as I can see, I will have to add the logic to add a regex array to the config file. I was thinking about giving the user access to some of the prebuilt regexes somehow. What would you suggest, do I use an array in the JSON file to chop the regex to make it easier to read and understand, or cut it short somewhere else (maybe a separate file with just the regex), since JSON and regular expression storage don't go very well together without a load of backslashes?

Even though I don't think it's worth converting to YAML for just this, we _could_ get by with treating the JSON as YAML somewhat easily.

**Comment by firecat53** [comment]
What about just using a separate config file 'customregex.py' that just contains those variables. Then if it exists, you can just `reg = importlib.import_module('customregex')` and set the variables from the file instead. Seems like it's easier doing that then trying to figure out escaping for either a JSON or ConfigParser config file. We can just put a note in the manpage for advanced usage and add a command line switch to generate the customregex.py file.

Thoughts?

**Comment by alter2000** [comment]
That seems like the best idea. Will get to it this weekend.

**Comment by firecat53** [comment]
Hold off until you see some commits either on develop or master adding keybindings to the config file. I did some significant refactoring yesterday that hasn't been pushed to Github yet and that might affect what you're working on!

**Comment by rslindee** [comment]
Just to add to this:

I personally don't have much of a use for scanning mailto: links in emails and I often find this clutters things up. I'd love to ignore mailto, either via modifying the regex or via something along the lines of a simple "--nomail" argument.

Thank you again for all your hard work on this!

**Comment by rafaeluriarte** [comment]
+1 for an argument to ignore mailto.... Anyone has managed to do it?

**Comment by alter2000** [comment]
I've finally got some free time now, so I'm fleshing out ideas to work on this week.

We could have configuration options in `$XDG_CONFIG_DIR/urlscan`:
 - inside `config.json`: PITA to write, edit and manage, would not recommend
 - inside a separate file (named e.g. `regex`) that overrides the default config
    - should this be a single regex or a Python expression we could evaluate into one?

And/or as a flag:
 - path to a file
 - Python regex string as argument

I don't know which one is the best fit, since for my use case I'm just hardcoding my regex into the file, although it would be useful to others.

**Comment by firecat53** [comment]
I think my vote is still for doing as I described above:

> What about just using a separate config file 'customregex.py' that just contains those variables. Then if it exists, you can just `reg = importlib.import_module('customregex')` and set the variables from the file instead. Seems like it's easier doing that then trying to figure out escaping for either a JSON or ConfigParser config file. We can just put a note in the manpage for advanced usage and add a command line switch to generate the customregex.py file.

**Comment by kylebarbour** [comment]
I think this issue might be pretty common. I integrate `urslcan` with `mutt`, and it gets its most usage with HTML email with embedded links. Picking some recent HTML emails and sending them through `urlscan` I wind up with multiple pages of links, many of which are are `mailto:`s or `href`s in HTML tags that give redundant links I'd like to exclude, sometimes surrounded by multiple pages of CSS code and other similar things that a regex could help exclude. I don't know if this would give a way to remove redundant links but that would be amazing as well.

**Comment by rpolve** [comment]
> And/or as a flag:
>     * path to a file
>     * Python regex string as argument

I'd prefer this approach as it can be generalized/repurposed for the most different use cases.

E.g. I have a keybinding for piping terminal buffer into urlscan, and it interprets stuff like `some_archive.zip` as URL, which I don't desire obviously.

It would help if I could just `--regex='http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'`.

I'll see if I can come up with a functional PR.

**Comment by firecat53** [comment]
@rpolve - Perhaps having the regex option available in two places: 1. In the existing config file for global regex changes. and 2. as a command line switch which would override the config file (for special use cases...like processing the terminal buffer vs general email links).

What do you think? Thanks for your interest!!

**Comment by rpolve** [comment]
> In the existing config file for global regex changes

Sorry, do you mean the `--genconf` one? Or something else?

**Comment by rpolve** [comment]
Hi. Did you have any chance to take a look at PR #102?

**Comment by firecat53** [comment]
Studying for promotional exam. It'll be a month or so before I sit down to any of projects. Sorry!
