### ISSUE TITLE
Hide help

### ISSUE THREAD

**Issue by rslindee** [firecat53/urlscan#80]
I find the "help" to be a little intrusive, especially when calling urlscan in a small tmux pane.

Would it be possible to add an argument to hide the help when calling urlscan (e.g. "--nohelp, -s")?

**Comment by firecat53** [comment]
Give the develop branch a try. F1 toggles help menu visibility, `--nohelp` or `-H` starts with menu hidden by default.

**Comment by rslindee** [comment]
Thank you for the quick reply! I grabbed the latest develop commit, built, and attempted to run, but received the following error:

Traceback (most recent call last):
  File "./urlscan", line 195, in <module>
    main()
  File "./urlscan", line 185, in main
    pipe=args.pipe)
TypeError: __init__() got an unexpected keyword argument 'nohelp'

**Comment by firecat53** [comment]
I can't reproduce that here. Can you step me through how you download/install? Here's what I did (Arch Python 3.7):

    git clone https://github.com/firecat53/urlscan.git
    cd urlscan
    git checkout develop
    python -m venv .venv
    source .venv/bin/activate
    pip install -e .
    urlscan <filename>

**Comment by rslindee** [comment]
Thank you for clarifying. After following your instructions for building/installing via pip, it appears to be working as expected. Looks great!

You may want to clarify the build instructions for others. I had basically ran "setup.py build", which gave me a bin directory containing a (non-working, evidently) urlscan executable.
