### ISSUE TITLE
urlscan.close_stdin() fails from mutt in xterm

### ISSUE THREAD

**Issue by NeoGeetz** [firecat53/urlscan#82]
I know there's another issue that was opened about 3 years back that seemed to go away but rebooting didn't do anything in my case.

I don't know if this is due to something mutt does to /dev/tty or an xterm thing but maybe if you can't reproduce it then I'll assume it might have something to do with my mutt install or something.

environment: xterm 344-1 mutt 1.11.3-2 urlscan 0.9.2-1

I can run urlscan with a file argument in xterm directly just fine, but the line
close_stdin()
at the end of process_input(fname)
causes the python traceback thing to happen when I pipe an email message into mutt
with the '|' keybinding. ("no device /dev/tty")

if I comment out close_stdin() at the end of process_input(fname) it works but then doesn't receive inputs ie like pressing down up or enter.

**Comment by firecat53** [comment]
Yeah, I can't reproduce this here...identical versions of all three programs (Arch, I'm assuming?). Tried in  xterm, urxvt, terminator and a tty and all worked fine using the mutt `| urlscan` command. Sounds like you've got something wonky in your environment....wish I could direct you where to look! Does it work in other terminals? What's the window manager or DE? How do you login...tty or login manager?

**Comment by NeoGeetz** [comment]
hey, thanks for trying at least. I must. window manager is awesome, I'll admit it's given me issues in the past. Yeah I'm also on Arch. I just tried it now in tty and same issue but if i run the command from the command prompt directly it's fine. Maybe it's my mutt settings or some kind of ncurses thing. Thanks for responding so quickly !
