### ISSUE TITLE
setup.py not installing man and doc information

### ISSUE THREAD

**Issue by Boruch-Baum** [firecat53/urlscan#84]
When running `python3 setup.py install --user` for version 0.9.2, the installer does successfully install the executable to ~/.local/bin, and does install an egg to ~/.local/lib/.... ; however the man pages are not installed to ~/.local/share/man/man1, and the doc files aren't installed ti ~/.local/share/doc/urlscan.

**Comment by firecat53** [comment]
I dug into this for awhile and determined that there is no easy way to make `python setup.py install` put the data_files items in the correct place. It is possible, but at the cost of complexity in setup.py. I think given that pip is available by default in both Python 2.x and 3.x now, I'll just remove the `setup.py install` method from the README as a recommended installation method. `pip install` gets all the extra files in the correct spot for root and user installs.

Thoughts?

**Comment by Boruch-Baum** [comment]
> Thoughts?

Sounds reasonable to me. In the bigger picture, if you're indicating that this is a bug in setup.py, could you file a bug for it?

**Comment by firecat53** [comment]
Oof...I'm not even sure I understand python packaging enough to make a coherent bug report! It's constantly changing and with most people using pip, I'm just not going to worry about. Thanks!
