### ISSUE TITLE
option to copy to 'real' clipboard (ie. not 'primary')

### ISSUE THREAD

**Issue by Boruch-Baum** [firecat53/urlscan#87]
This could be implemented as a parameter to the option `-C`, or as an item in a config file. What I've done locally is change line 331 of file `urlchoose.py`:

            cmds = ("xsel -ib", "xclip -i -selection clipboard")

**Comment by firecat53** [comment]
Yeah, I'll have to think about the best way to handle it. Thanks for the request.

**Comment by firecat53** [comment]
This commit should work for you. `C` to copy to clipboard, `P` to copy to primary selection.

**Comment by Boruch-Baum** [comment]
On 2019-04-04 09:53, Scott Hansen wrote:
>    This commit should work for you. C to copy to clipboard, P to copy to
>    primary selection.

Thanks. I hope others find it useful, too.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
