### ISSUE TITLE
wl-clipboard support

### ISSUE THREAD

**Issue by ainola** [firecat53/urlscan#88]
For those of us using wayland, it would be nice to have wl-clipboard support. `pass` handles this by [abstracting the clipboard command](https://git.zx2c4.com/password-store/commit/?id=b0b784b1a57c0b06936e6f5d6560712b4b810cd3); Perhaps urlscan could utilize a similar technique?

**Comment by firecat53** [comment]
I'm open to PRs on this. I don't use Wayland. It's possible I might at some point in the future so I'll definitely leave this open! Thanks.
