### ISSUE TITLE
Quit after select

### ISSUE THREAD

**Issue by marcvs** [firecat53/urlscan#95]
Hi There,

nice stuff. If would be nice to have a '-q' option so that urlscan quits after the link was opened in the browser.

**Comment by firecat53** [comment]
Sure. That's pretty easy to do. Should it also close when copying to clipboard, or just opening in browser?

**Comment by marcvs** [comment]
I guess this option would be useful for both: copy to clipboard and browser.
Maybe this would be en/disabled by a new cmdline option anyways, right?
