### ISSUE TITLE
Extract URL from headers (feature request)

### ISSUE THREAD

**Issue by WhilelM** [firecat53/urlscan#97]
Thanks for this usefull software.

Is it possible to extract URL from headers too ?

`Content-Type: text/plain; charset="utf-8"                                                                                                     
MIME-Version: 1.0                                                                                                                             
Content-Transfer-Encoding: 7bit                                                                                                               
Date: Fri, 10 Jul 2020 19:16:02 -0000                                                                                                         
To: whilelm@littlegr83                                                                                                                        
From: By The Associated Press <whilelm@littlegr83>                                                                                            
Subject: Dutch Government Sues Russia Over Downing of Flight MH17                                                                             
Message-ID: dutch-government-sues-russia-over-downing-of-flight-mh17                                                                          
User-Agent: feed2exec (0.15.0)                                                                                                                
Precedence: list                                                                                                                              
Auto-Submitted: auto-generated                                                                                                                
Archived-At: https://www.nytimes.com/video/world/europe/100000007233443/netherlands-russia-court-malaysia-airlines-flight-17.html             

The Dutch foreign minister said the Netherlands was taking Russia to the European Court of Human Rights for the downing of Malaysia Airlines Flight 17 over Ukraine in 2014, killing 298 people.
`

I would like to be able to open https://www.nytimes.com/video/world/europe/100000007233443/netherlands-russia-court-malaysia-airlines-flight-17.html from this example.

Thanks for your consideration.

**Comment by firecat53** [comment]
Can you please tar and attach or email the example? It's much easier to
work with the email in email format instead of pasted text. Thanks!

**Comment by WhilelM** [comment]
Le vendredi 10 juil. 2020 à 16:41:58 (-0700), Scott Hansen a écrit :
> Can you please tar and attach or email the example? It's much easier to
> work with the email in email format instead of pasted text. Thanks!

Sure, is it OK with this one ?

-- 
"Vous n'avez rien à cacher. Moi non plus. C'est pour ça que je suis habillé."

**Comment by firecat53** [comment]
Yes that's fine. I'll work on this as time permits. It appears that the 'Archived-At' and some of the 'List-' headers might be the only ones that would typically have a URL to scan. [List of email headers](https://www.iana.org/assignments/message-headers/message-headers.xhtml).

**Comment by firecat53** [comment]
Better late than never! Try the `headers` branch and see if that adds the functionality you are looking for. Pass `--headers` to urlscan to active the feature.
